research_task:
  description: >
    Conduct a thorough research about finances and the current state of the market.
    Make sure to include the most relevant information and data for {problem}.
    Focus on the following topics:
    - Current trends in the financial market
    - Key players in the market
    - Recent developments and news
    - Future predictions and forecasts
    - Potential risks and challenges
    - Opportunities for growth and investment
    - Regulatory changes and their impact
    - Technological advancements and their implications
    - Global economic factors affecting the market
    - Historical data and its relevance to current trends
  expected_output: >
    A list with 10 bullet points of the most relevant information about the financial market.
    Each bullet point should be a short summary of the information found.

  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
